import { TypographyOptions } from '@mui/material/styles/createTypography';

export const MUI_TYPOGRAPHY_LIGHT_THEME: TypographyOptions = {
  fontSize: 14,
  fontFamily: 'var(--fontPrimary)',
  h1: {
    fontFamily: 'var(--fontSecondary)',
    fontWeight: 600,
    fontSize: 36,
    lineHeight: 1.46,
    color: 'var(--color-coal-black)',
  },
  h2: {
    fontSize: 26,
    fontWeight: 600,
    fontFamily: 'var(--fontSecondary)',
    lineHeight: 1.7,
    color: 'var(--color-coal-black)',
  },
  h3: {
    fontFamily: 'var(--fontSecondary)',
    fontSize: 24,
    fontWeight: 600,
    lineHeight: 1.25,
    color: 'var(--color-coal-black)',
  },
  h4: {
    fontFamily: 'var(--fontSecondary)',
    fontSize: 20,
    fontWeight: 600,
    lineHeight: 1.62,
    color: 'var(--color-coal-black)',
  },
  subtitle1: {
    fontFamily: 'var(--fontSecondary)',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '18px',
    lineHeight: '28px',
    color: 'var(--color-coal-black)',
  },
  subtitle2: {
    fontFamily: 'var(--fontSecondary)',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '16px',
    lineHeight: '24px',
    color: 'var(--color-coal-black)',
  },
  body1: {
    fontFamily: 'var(--fontPrimary)',
    fontStyle: 'normal',
    fontWeight: 300,
    fontSize: '16px',
    lineHeight: '24px',
    color: 'var(--color-coal-black)',
  },
  body2: {
    fontFamily: 'var(--fontPrimary)',
    fontStyle: 'normal',
    fontWeight: 300,
    fontSize: '14px',
    lineHeight: '24px',
    color: 'var(--color-coal-black)',
  },
  caption: {
    fontFamily: 'var(--fontPrimary)',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '12px',
    lineHeight: '20px',
    color: 'var(--color-coal-black)',
  },
  button: {
    fontFamily: 'var(--fontPrimary)',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '14px',
    lineHeight: '24px',
    textTransform: 'none',
    color: 'var(--color-coal-black)',
  },
};
